// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BfniqIJPOkOfr8XwiKTR-ldPYUZnH-Y',
    appId: '1:103695207287:web:4cdb071c7dfee96d76ef72',
    messagingSenderId: '103695207287',
    projectId: 'myapp-70348',
    authDomain: 'myapp-70348.firebaseapp.com',
    storageBucket: 'myapp-70348.appspot.com',
    measurementId: 'G-QNGJ7EPWZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIwXlpRpg-4kEEV3Dam60_gcI_0y-jJ7w',
    appId: '1:103695207287:android:f93a1c52c17e5ba976ef72',
    messagingSenderId: '103695207287',
    projectId: 'myapp-70348',
    storageBucket: 'myapp-70348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjNrp5EGjz1p7pBbGNVADPNhQfn5EGUM',
    appId: '1:103695207287:ios:7f6d26c2dc0c4fd376ef72',
    messagingSenderId: '103695207287',
    projectId: 'myapp-70348',
    storageBucket: 'myapp-70348.appspot.com',
    iosBundleId: 'com.example.vakum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjNrp5EGjz1p7pBbGNVADPNhQfn5EGUM',
    appId: '1:103695207287:ios:5c62878ed42a21a176ef72',
    messagingSenderId: '103695207287',
    projectId: 'myapp-70348',
    storageBucket: 'myapp-70348.appspot.com',
    iosBundleId: 'com.example.vakum.RunnerTests',
  );
}
