// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFf4dAY10pjR6biZHXwE1XuTfizCw2g0',
    appId: '1:209117327158:web:785a8143d96cd5ccab8d97',
    messagingSenderId: '209117327158',
    projectId: 'vacum-58709',
    authDomain: 'vacum-58709.firebaseapp.com',
    storageBucket: 'vacum-58709.appspot.com',
    measurementId: 'G-P2L4YBMY3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDncscibzuE8NKz-j05DjaUMIWdCLj_1v0',
    appId: '1:209117327158:android:1778caab89b5dc88ab8d97',
    messagingSenderId: '209117327158',
    projectId: 'vacum-58709',
    storageBucket: 'vacum-58709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MXropeapFTkcmwnJ_BL0hSp93fYIBZs',
    appId: '1:209117327158:ios:1145c4f9a4dd6ae0ab8d97',
    messagingSenderId: '209117327158',
    projectId: 'vacum-58709',
    storageBucket: 'vacum-58709.appspot.com',
    iosBundleId: 'com.example.vakum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2MXropeapFTkcmwnJ_BL0hSp93fYIBZs',
    appId: '1:209117327158:ios:1145c4f9a4dd6ae0ab8d97',
    messagingSenderId: '209117327158',
    projectId: 'vacum-58709',
    storageBucket: 'vacum-58709.appspot.com',
    iosBundleId: 'com.example.vakum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDFf4dAY10pjR6biZHXwE1XuTfizCw2g0',
    appId: '1:209117327158:web:a69786064951722dab8d97',
    messagingSenderId: '209117327158',
    projectId: 'vacum-58709',
    authDomain: 'vacum-58709.firebaseapp.com',
    storageBucket: 'vacum-58709.appspot.com',
    measurementId: 'G-J85GL0NX3C',
  );

}